name: snowpark_xgboost_tpc
# channels:
#   - pip
dependencies:
  - python=3.8
  - sqlalchemy
  - snowflake-snowpark-python
  - ipykernel
  - pyarrow
  - numpy
  - scikit-learn
  - pandas
  - joblib
  - cachetools
  - xgboost
  - snowflake-sqlalchemy
